# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Qoot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  # Pods for Qoot

end
